# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 666eb7f81a8ffd8dc8233c61a4a7a2f658b0bbc9c31ea678e6ac7cf358b280d998889c5510c29a974bcb4fdcab219e98a2f0b0a6d978b530125e4e6e13d82881

test:
  secret_key_base: 9afbf7ef76e4a9ff7d428cb37149f4528d59c6fbb6cb7937ecb23d660f2701e7bcc3c8772841b22cd2b8f84e789a2b2cea44076f1ac4ce3f12cc3131f3584766

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
